### ISSUE TITLE
Error Installing Nektar++ on OS X through Homebrew

### ISSUE THREAD

**Issue by GiulioMT** [mdave/homebrew-nektar#6]
I am trying to install Nektar++ on my macbook using the homebrew command "brew tap mdave/nektar && brew install nektar" and I incurred in the following error

Last 15 lines from /Users/giuliomoscatoba/Library/Logs/Homebrew/nektar/01.cmake:
-- -- Found Boost iostreams library: /opt/homebrew/lib/libboost_iostreams-mt.dylib
-- -- Found Boost filesystem library: /opt/homebrew/lib/libboost_filesystem-mt.dylib
-- -- Found Boost system library: /opt/homebrew/lib/libboost_system-mt.dylib
-- -- Found Boost program_options library: /opt/homebrew/lib/libboost_program_options-mt.dylib
-- -- Found Boost regex library: /opt/homebrew/lib/libboost_regex-mt.dylib
-- Found PythonInterp: /opt/homebrew/opt/python@3.10/bin/python3
CMake Error at cmake/FindPythonLibsNew.cmake:86 (message):
  Python config failure:

Call Stack (most recent call first):
  cmake/ThirdPartyPython.cmake:31 (FIND_PACKAGE)
  CMakeLists.txt:252 (INCLUDE)

-- Configuring incomplete, errors occurred!

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/mdave/homebrew-nektar/issues

Any suggestion on what the issue might be? I am not sure whether this might be relevant but I have the M1 max macbook pro. Please let me know, thank you.

**Comment by mdave** [comment]
@GiulioMT Thanks for reporting this! Sorry that I did not respond so this is likely not an issue any more, but I did fix this in #7, so a `brew update` should solve the issue. (I've also updated this tap to 5.4.0). The issue was that homebrew's core Python paths had changed which broke the CMake configuration.
